### ISSUE TITLE
Making it suitable to run on FreeBSD

### ISSUE THREAD

**Issue by devlaam** [iotaledger/hive.go#216]
## Description

hive.go is used for hornet. The only thing failing to compile hornet from source on FreeBSD is a platform file "constants_freebsd.go" in this dependency. Its content can be identical to "constants_darwin.go". 

## Motivation

This would enlarge the user base.

## Are you planning to do it yourself in a pull request?

I could, but it is such a minimal change, it would be not worth it. The developers can perform it in a split second.

**Comment by muXxer** [comment]
Added with #280 
Sorry I didn't see your issue earlier :sweat_smile:
